[package]
name = "chaospass"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
rand = { version = "0.8", features = ["small_rng"] }
zeroize = { version = "1.7", features = ["derive"] }
arboard = "3.3"

[profile.release]
opt-level = "z"     
lto = true          
codegen-units = 1   
panic = "abort"     
strip = true        